### ISSUE TITLE
Update for swift 4

### ISSUE THREAD

**Issue by pahanius** [JotaMelo/JMMaskTextField-Swift#1]
Hello
When is the upgrade to SWIFT 4 expected?

**Comment by gabrielvieira** [comment]
@PAHANIUS i am not using cocoapods, but with manual install its working with swift 4

**Comment by JotaMelo** [comment]
Hey, I can’t work on the project anymore but there was a pull request about a month ago that should’ve taken care of most warnings on Swift 4 https://github.com/JotaMelo/JMMaskTextField-Swift/pull/2

**Comment by pahanius** [comment]
Thanks )
